version: '3'

services:
  performance-objectmapper:
    image: performance-objectmapper-app:latest
    environment:
      JAVA_OPTIONS: -Xmx512M
    ports:
      - '8080:8080'
    healthcheck:
      test:  "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      retries: 10
      timeout: 2s
      interval: 5s
      start_interval: 2s
  apache-bench:
    image: jordi/ab
    depends_on:
      performance-objectmapper:
        condition: service_healthy
    command:
      - -k
      - '-c 4'
      - '-n 100'
      - 'http://performance-objectmapper:8080/angebote'
