version: '3'

include:
  - benchmarks/angebote_benchmark.yml

services:
  performance-app:
    build: ../
    environment:
      JAVA_OPTIONS: -Xmx512M
      OBJECTMAPPERFACTORY: recreating
    ports:
      - '8080:8080'
    healthcheck:
      test:  "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      retries: 10
      timeout: 2s
      interval: 5s
      start_interval: 2s
