version: '3'

include:
  - benchmarks/verbindungen_benchmark.yml

services:
  performance-app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      JAVA_OPTIONS: -Xmx512M
      PERSISTENT_CONNECTIONS: false
    ports:
      - '8080:8080'
    healthcheck:
      test:  "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      retries: 10
      timeout: 2s
      interval: 5s
      start_interval: 2s
  verbindung-service:
    image: nginx
    ports:
      - '8443:8443'
    volumes:
     - ./nginx/templates:/etc/nginx/templates
     - ./nginx/json:/usr/share/nginx/json
     - ../certs:/etc/nginx/certs
