version: '3'

services:
  angebote-bench-warmup:
    image: jordi/ab
    depends_on:
      performance-app:
        condition: service_healthy
    command:
      - -k
      - '-c 2'
      - '-n 50'
      - 'http://performance-app:8080/angebote'
  angebote-bench-full:
    image: jordi/ab
    depends_on:
      angebote-bench-warmup:
        condition: service_completed_successfully
    command:
      - -k
      - '-c 4'
      - '-n 100'
      - 'http://performance-app:8080/angebote'
