version: '3'

services:
  apache-bench-warmup:
    image: jordi/ab
    depends_on:
      performance-objectmapper:
        condition: service_healthy
    command:
      - -k
      - '-c 2'
      - '-n 10'
      - 'http://performance-objectmapper:8080/angebote'
  apache-bench-full:
    image: jordi/ab
    depends_on:
      apache-bench-warmup:
        condition: service_completed_successfully
    command:
      - -k
      - '-c 4'
      - '-n 100'
      - 'http://performance-objectmapper:8080/angebote'
